### ISSUE TITLE
[Feature request] add failure count for for alerting

### ISSUE THREAD

**Issue by MrClayPole** [ibbaa/keepitup#11]
Would be nice if you could say set the monitor interval to say 2 mins but only alert if there are 3 consecutive failures to avoid a single failure from tripping an alert.

**Comment by ibbaa** [comment]
It's a good idea, thanks. The feature request list is a bit long at the moment, but I keep into consideration.

**Comment by ibbaa** [comment]
With 1.4.0 release failures are tracked from last success on and it is configurable to notify only after X failures
