### ISSUE TITLE
[Feature request] Move ping amount to the settings of the server

### ISSUE THREAD

**Issue by baack** [ibbaa/keepitup#6]
[Feature request] Move ping amount to the settings of the server.

This way different servers will be possible to ping different amount of times (because some can be more important or have worse internet connection). The new checkbox from #5 if implemented can be also used in server's settings, not the app's settings.

**Comment by ibbaa** [comment]
This can be done and makes perfect sense. It's always a decision to put something to the server or the global settings (the latter being less effort). I'm the only developer on this project and spend time when I'm able to and I'm currently busy with time scheduling feature, which will take quite a while. After that I'm thinking about ping enhancements.

**Comment by baack** [comment]
I would like to note, that your application is the only one I know for making this general pings/requests that is FLOSS and not outdated. So, that's why it would be great if this project would improve with new features and new users.

**Comment by ibbaa** [comment]
With 1.4.0 release ping and connect count can now be set per network task
