### ISSUE TITLE
[Feature request] Option to set the package size for ping packages

### ISSUE THREAD

**Issue by baack** [ibbaa/keepitup#9]
[Feature request] Option to set the package size for ping packages.

It is useful when firewall of the server is set in the mode of replying only to pings with custom package size.
This feature is widely supported: 
on GNU/Linux with `-s` option,
on Windows with `-l` option.

Can this be implemented in the case of this android app?

**Comment by ibbaa** [comment]
This sounds reasonable and Android is Linux at the end (also completely different as one is used to). The app call the ping command under "/system/bin" and I think this standard option should be supported. So the effort is mainly providing a gui for it.

**Comment by ibbaa** [comment]
With 1.4.0 release the ping package size is configurable per network task
